name: edu_ai
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none'

# Version and build number for the application
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^4.17.5
  flutter_gemini: 2.0.4
  dash_chat_2: ^0.0.20
  youtube_player_flutter: ^8.0.0
  flutter_inappwebview: ^5.3.2
  collection: ^1.16.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Adding assets
  assets:
    - assets/

  # Example for adding custom fonts (if needed in future)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
